flowchart TB
  NET((NAT1 / Internet<br/>ISP Gi3/0 DHCP)):::cloud
  ISP[ISP<br/>Gi3/0 DHCP - outside<br/>Gi1/0 20.25.6.1/30<br/>Gi2/0 20.25.97.1/30]
  R1[R1 - CISCO-SRV<br/>Gi1/0 20.25.6.2/30 - NAT outside<br/>Gi2/0.10 10.25.6.1/25 - NAT inside]
  SW[SW-1 - Cisco IOSvL2<br/>Gi0/0 trunk VLAN 10<br/>Gi0/1 access VLAN 10]
  PC[windows10-1<br/>DHCP 10.25.6.11/25<br/>VPN 10.25.98.10/32]
  FG[FortiGate 7.0.9<br/>WAN port1 20.25.97.2/30<br/>LAN port2 10.6.97.1/28]
  SRV[web-server-lab-1<br/>10.6.97.2/28<br/>TCP 22 and 443]
  NET --- ISP
  ISP ---|20.25.6.0/30| R1
  ISP ---|20.25.97.0/30| FG
  R1 ---|"802.1Q VLAN 10 (port UNKNOWN / NEEDS VERIFICATION)"| SW
  SW --- PC
  FG ---|10.6.97.0/28| SRV
  classDef cloud fill:#e8f1ff,stroke:#4a76c9
